version: "3.7"
services:
  webserver:
    image: nginx
    container_name: ${COMPOSE_PROJECT_NAME}_webserver
    restart: always
    volumes:
      - ./application:/var/www
      - ./configuration/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - 80:80
      - 443:443
    networks:
      - network
    links:
      - laravel
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    container_name: ${COMPOSE_PROJECT_NAME}_laravel
    command: ["/wait-for-it.sh", "${COMPOSE_PROJECT_NAME}_mysql:3306", "--", "/docker-entry.sh"]
    volumes:
      - ./application:/var/www
      - ./configuration/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    links:
      - mysql
    networks:
      - network
  mysql:
    image: mysql:5.7.22
    container_name: ${COMPOSE_PROJECT_NAME}_mysql
    restart: always
    # expose:
    #   - 3306
    environment:
      - MYSQL_DATABASE=homestead
      - MYSQL_ROOT_PASSWORD=Pro@123
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
    ports:
      - 3306:3306
    volumes:
      - ./configuration/mysql/low-memory-my.cnf:/etc/mysql/my.cnf
      - ./dbdata/mysql:/var/lib/mysql
    networks:
      - network
  adminer:
    image: adminer
    container_name: ${COMPOSE_PROJECT_NAME}_adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - network
  redis:
    image: redis
    container_name: ${COMPOSE_PROJECT_NAME}_redis_cache
    environment:
      - ALLOW_EMPTY_PASSWORDS=yes
    expose:
      - 6379
    networks:
      - network
networks:
  network:
    driver: bridge
